// <auto-generated />
namespace ConcertTicketsWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createCreditCardmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createCreditCardmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201711081517202_create CreditCard model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
